---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox1
  labels:
    app: busybox1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: busybox1
  template:
    metadata:
      labels:
        app: busybox1
        blinkt: show
        blinktColor: "000B87"
    spec:
      containers:
      - image: busybox
        command:
          - sleep
          - "200"
        imagePullPolicy: IfNotPresent
        name: busybox
      restartPolicy: Always
